# SDL2 shim for Emscripten — uses -sUSE_SDL=2 port.
if (NOT EMSCRIPTEN)
    list(REMOVE_ITEM CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    find_package(SDL2 ${SDL2_FIND_VERSION})
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    return()
endif()

set(SDL2_FOUND TRUE)
set(SDL2_VERSION "2.28.0")
set(SDL2_LIBRARY "")
set(SDL2_LIBRARIES "")
set(SDL2_INCLUDE_DIR "")
set(SDL2_INCLUDE_DIRS "")

if (NOT TARGET SDL2::SDL2)
    add_library(SDL2::SDL2 INTERFACE IMPORTED GLOBAL)
    target_compile_options(SDL2::SDL2 INTERFACE "SHELL:-sUSE_SDL=2")
    target_link_options(SDL2::SDL2 INTERFACE "SHELL:-sUSE_SDL=2")
endif()
if (NOT TARGET SDL2::SDL2main)
    add_library(SDL2::SDL2main INTERFACE IMPORTED GLOBAL)
    target_link_libraries(SDL2::SDL2main INTERFACE SDL2::SDL2)
endif()
