if (NOT EMSCRIPTEN)
    list(REMOVE_ITEM CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    find_package(EXPAT ${EXPAT_FIND_VERSION})
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    return()
endif()
# Headless replay probably doesn't parse XML at runtime — stub as empty interface.
set(EXPAT_FOUND TRUE)
set(EXPAT_VERSION "2.5.0")
set(EXPAT_LIBRARIES "")
set(EXPAT_INCLUDE_DIRS "")
if (NOT TARGET EXPAT::EXPAT)
    add_library(EXPAT::EXPAT INTERFACE IMPORTED GLOBAL)
endif()
