if (NOT EMSCRIPTEN)
    list(REMOVE_ITEM CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    find_package(Fontconfig ${Fontconfig_FIND_VERSION})
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
    return()
endif()
# Headless replay doesn't need font config discovery — stub as empty interface.
set(Fontconfig_FOUND TRUE)
set(Fontconfig_VERSION "2.14.0")
set(Fontconfig_LIBRARIES "")
set(Fontconfig_INCLUDE_DIRS "")
if (NOT TARGET Fontconfig::Fontconfig)
    add_library(Fontconfig::Fontconfig INTERFACE IMPORTED GLOBAL)
endif()
